add Roles, impl security
NataliaKurhanska/book-store pull request #9
Opened 2023-12-13 11:11 UTC by NataliaKurhanska

2023-12-13 11:14 UTC, NataliaKurhanska commented
Привіт! Чому не можна зробити доступ до каталогу книг відкритим для всіх? 
      .requestMatchers(HttpMethod.GET, "/api/books")
      .permitAll()

2023-12-13 15:33 UTC, kerrrusha commented
> Привіт! Чому не можна зробити доступ до каталогу книг відкритим для всіх? .requestMatchers(HttpMethod.GET, "/api/books") .permitAll()

ментори відповідають на питання лише в чатах на платформі, продублюй будь-ласка там

2023-12-13 15:34 UTC, kerrrusha requested changes
almost perfect

2023-12-13 15:34 UTC, kerrrusha commented on src/main/java/bookstore/config/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**")
add swagger

2023-12-14 12:22 UTC, Sanderfuck approved these changes

2023-12-22 16:29 UTC, merged